name: test-report
description: Generates test reports and code coverage reports for .NET tests
inputs:
  TestResultsDirectory:
    description: "Directory where test results are stored"
    required: true
    default: "./TestResults"
  CoverageReportDirectory:
    description: "Directory where code coverage reports will be generated"
    required: true
    default: "./CoverageReports"
  shell:
    description: "Shell to use for running the steps (e.g., bash, pwsh)"
    required: false
    default: "bash"
runs:
  using: "composite"
  steps:
    - name: Install Required .NET Tools for Report Generation
      shell: ${{ inputs.shell }}
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet tool install --global dotnet-reportgenerator-globaltool
    
    - name: Merge Coverage Reports
      shell: ${{ inputs.shell }}
      run: |
        dotnet-coverage merge ${{ inputs.TestResultsDirectory }}/**/*.cobertura.xml -f cobertura -o ${{ inputs.CoverageReportDirectory }}/merged.cobertura.xml
    
    - name: Generate Test Report
      shell: ${{ inputs.shell }}
      run: |
        reportgenerator -reports:"${{ inputs.CoverageReportDirectory }}/merged.cobertura.xml" -targetdir:"${{ inputs.CoverageReportDirectory }}/report" -filefilters:"-**\Generated\**\*.cs;-**\Migrations\**\*.cs"  -classfilters:"-Microsoft.*;-System.*"
    
    - name: Upload Test Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ inputs.CoverageReportDirectory }}/report
        


        
