// <auto-generated />
using System;
using ChatService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ChatService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatService.Domain.Entities.AI.TicketAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Component")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("ErrorCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("LastReanalysedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("PreventionTips")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ProblemAnalysedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProblemSummary")
                        .HasColumnType("text");

                    b.Property<int>("ReanalysisCount")
                        .HasColumnType("integer");

                    b.Property<string>("RootCause")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SolutionAnalysedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("SolutionSteps")
                        .HasColumnType("text[]");

                    b.Property<string>("SolutionSummary")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TicketAnalysis");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.AI.TicketEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSemanticSearchable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProblemEmbeddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProblemEmbeddingSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("ProblemVector")
                        .IsRequired()
                        .HasColumnType("vector");

                    b.Property<DateTime?>("SolutionEmbeddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SolutionEmbeddingSource")
                        .HasColumnType("text");

                    b.Property<Vector>("SolutionVector")
                        .HasColumnType("vector");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("TicketEmbedding");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.ConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscalatedTicketId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.DomainDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DomainDetails");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.FaqEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FaqEntries");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFromUser")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.AI.TicketEmbedding", b =>
                {
                    b.HasOne("ChatService.Domain.Entities.AI.TicketAnalysis", "Analysis")
                        .WithOne("Embedding")
                        .HasForeignKey("ChatService.Domain.Entities.AI.TicketEmbedding", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.MessageEntity", b =>
                {
                    b.HasOne("ChatService.Domain.Entities.ConversationEntity", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatService.Domain.Entities.AI.TicketAnalysis", b =>
                {
                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("ChatService.Domain.Entities.ConversationEntity", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
