# Use the official Nginx image as the base
FROM nginx:alpine

# Copy custom nginx config
COPY ./docker/Koppar/nginx.conf /etc/nginx/nginx.conf

# Copy the HTML file to the default Nginx public directory
COPY ./docker/Koppar/koppar_coffee_responsive.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Start Nginx (default CMD is fine)
