name: Build Release
description: Build and test the solution for release

on:
  pull_request:
    branches: [main]

jobs:
  Build_Release:
    name: Build and Test for Release
    runs-on: ubuntu-latest
    env:
      configuration: Release
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Solution
        uses: ./.github/actions/dotnet-steps
        with:
          configuration: ${{ env.configuration }}
          solution-file: ./src/CCP.slnx
          shell: bash

      - name: Unit Tests
        uses: ./.github/actions/dotnet-tests
        with:
          configuration: ${{ env.configuration }}
          solution-file: ./src/CCP.slnx
          steps: '["unit-tests", "integration-tests"]'
          shell: bash
